#context-path不同版本配置;boot 1.x版本：server.context-path=/demo; 2.x版本:server.servlet.context-path=/demo
server:
  port: 8090
  servlet:
    context-path: /thinking
  multipart:
    enable: true
    max-file-size: 20MB
    max-request-size: 200MB


spring:
  thymeleaf:
    cache: false #缓冲的配置
    check-template: true
    check-template-location: true
    enabled: true  #开启MVC thymeleaf 视图解析
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: test
    #url: jdbc:mysql://47.110.153.104:3306/enjoy_life?serverTimezone=GMT
    url: jdbc:mysql://localhost:3306/enjoy_life?serverTimezone=GMT
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 3600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: enjoy.life.entity  # 注意：对应实体类的路径

# 打印sql
logging:
  level:
    enjoy.life.mapper : debug

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#全局属性配置(Canonical names should be kebab-case ('-' separated))
global:
  pageSize: 5
  successAdd: 添加成功
  successUpdate: 修改成功
  successDelete: 刪除成功
  successImport: 导入成功
  errorAdd: 添加失败
  errorUpdate: 修改失败
  errorDelete: 刪除失败
  errorImport: 导入失败
  uploadPath: D:/upload/
  #uploadPath: C:/tomcat/upload/
  fileRequestUrl: /files/**

